### ISSUE TITLE
Memory usage issues

### ISSUE THREAD

**Issue by EdoEquin0x** [yuma140902/UpToDateMod1.7.10#12]
Hello, i've noticed that with this mod installed, the memory used by Minecraft is far greater than without it. I also noticed that the ram doesn't clear up after a while, so the game always end with a outofmemory crash

**Comment by yuma140902** [comment]
Hi. I compared Forge only environment and Forge+UpToDateMod environment. When no mod was installed, the maximum RAM usage was about 1000MB, and when this mod was installed, it was about 1100MB. I don't think this is so huge amount. Tell me exactly how much memory was used.
I think allocating more RAM to Minecraft will work in this case. Also see if the game can launch with other mods.
I will check if there is any memory leak later just in case.

**Comment by EdoEquin0x** [comment]
Well, we tried with some other mods (Biome O plenty, Backpack, this kind of mods) and 4Gb of memory allocated to the game, and the game ended up crashing because of the outofmemory error. This issues has been fixed by deleting UpToDate mods.

**Comment by yuma140902** [comment]
Try lanching with only UpToDateMod and see how much memory is used. I think this will clear whether the problem is this mod or not.
