### ISSUE TITLE
Missing Config Options and Netherlicous Compatibility.

### ISSUE THREAD

**Issue by MagmaSlime123** [yuma140902/UpToDateMod1.7.10#15]
Smooth Quartz and Smooth Sandstone have no toggle in the config. 

Et Futurum, UTD (UpToDate) and Netherlicous all have bone blocks. It'd be nice if we could choose what bone block is used for fossil generation, to prevent conflicts.

Since Et Futurum doesn't have dimension support, it'd be nice if we could have control over Et Futurum's generation as well.

**Comment by yuma140902** [comment]
As I have written in CurseForge, no request is accepted.
But I agree with you in the point that there are multiple backporting mods and that there are duplicate blocks and items. It would be good if you or someone else make a unifying mod for them like InstantUnify and UniDict solving duplicate ores and metals.

**Comment by MagmaSlime123** [comment]
Built in compatibility would be better since I doubt anyone else would do that. Not really any point in either mod if they won't work with each other.
