### ISSUE TITLE
Failing to download client.jar files for 1.12.2 and 1.15.2

### ISSUE THREAD

**Issue by syndicate25** [yuma140902/UpToDateMod1.7.10#17]
The mod has suddenly stopped downloading the required minecraft-client-1.12.2.jar and minecraft-client-1.15.2.jar, which halts the loading process of those downloading the mod (or a modpack with this mod) for the first time.

There are no issues discovered so far with those who already use the UpToDate mod.

You can manually work around this by downloading those files with the links in the popups, and put them in /uptodate/dlcache/ but this can be a challenge for some users. This used to be an automatic process, so I'm not sure why it suddenly stopped working.

![image](https://user-images.githubusercontent.com/22588398/188750496-993f4c40-9af8-48b9-9ba8-2063dba8f04a.png)

**Comment by KAMKEEL** [comment]
Make sure the downloads are in your `.minecraft/uptodate` directory. If you have your load instance running FROM any other directory, it's looking in the `.minecraft` folder. I don't know why that is. ALSO make sure your directories are EXACTLY how they should be in terms of folder name

**Comment by yuma140902** [comment]
I think v2.3.12 fixes this.
If not, please re-open this issue.
