### ISSUE TITLE
[質問]当Modを使用した収益の発生する動画の作成について

### ISSUE THREAD

**Issue by MilkNum2** [yuma140902/UpToDateMod1.7.10#18]
突然の連絡失礼します.
こちらのModを使用し動画を撮影し、動画サイトに収益が発生する状態で投稿したいのですが、動画の収益化はModのCC BY-NC-SA 4.0における商用利用に分類されますでしょうか？

**Comment by yuma140902** [comment]
商用利用には当たりません。

その理由は次のとおりです。

CC BY-NC-SA 4.0は、ライセンス対象物とその翻案物を表示・非営利・継承の条件のもとで自由に作成・公開してよいというライセンスです。

ライセンス対象物とはここでは私の書いたソースコードです。テクスチャやサウンドについては私の著作物ではなく、現にこのMODには含まれていません(Mojangのサーバーから自動ダウンロードしています)。

MilkNum2さんの作成する動画が私のソースコードの翻案物であるとは言えないと思います。

したがって、MilkNum2さんの作成する動画はライセンス対象物の翻案物ではないため、CC BY-NC-SA 4.0の対象とはなりません。

※他のMOD製作者さんは他の考え方をする場合があります。  
※これはあくまでもこのMODに限った話です。このMODは自作のテクスチャやサウンドを一切含まない特殊な形態なので...

**Comment by MilkNum2** [comment]
お忙しい中、ご丁寧に回答してくださいましてありがとうございます。
