### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 1ost** [yuma140902/UpToDateMod1.7.10#6]
if you get stuck inside granite, diorite, andesite you enter in a crash loop

**Comment by yuma140902** [comment]
Is that caused only by this mod’s blocks, or also by vanilla blocks?  If it is caused by other mods’ blocks and vanilla blocks, this issue is not by this mod. Maybe it is a vanilla bug.

**Comment by 1ost** [comment]
Especially concrete , diorite and granite from your mod . The other mods i've tried to get stuck into seem to not crash

**Comment by yuma140902** [comment]
I see. Can you send me the crash log? I need crash report in crash-reports directory and ‘latest.log’ file in logs directory.

**Comment by 1ost** [comment]
[crash-2019-11-11_22.54.40-client (1).txt](https://github.com/yuma140902/UpToDateMod1.7.10/files/3855495/crash-2019-11-11_22.54.40-client.1.txt)

[2019-11-12-7.log](https://github.com/yuma140902/UpToDateMod1.7.10/files/3855497/2019-11-12-7.log)

**Comment by 1ost** [comment]
Also just to add , i've tried doing this with only your mod in the mods directory , and it was still crashing

**Comment by yuma140902** [comment]
I read through the logs but I couldn’t find the cause of this issue. Sorry. Try to use MCEdit to remove the block you stuck inside, or roll back the world from backup. 
(I suspect that this issue is a vanilla bug.)

**Comment by 1ost** [comment]
hmm okay , but the crash happens only with these 3 blocks . The other blocks from your mod works just fine
