### ISSUE TITLE
Freezes with Wither Rose Generation

### ISSUE THREAD

**Issue by DarianLStephens** [yuma140902/UpToDateMod1.7.10#9]
If you have a creature die due to the Wither effect, the game will sometimes freeze, and sometimes successfully make the Wither Rose.
It stays frozen for quite some time, and it can take upward of a minute to recover.
After the game unfreezes, a Wither Rose will have been placed.
Note that the client doesn't freeze, so you can still move about this frozen world; It's something on the server's side.

Tested with literally nothing but Forge and UpToDateMod 2.1.1.

**Comment by yuma140902** [comment]
Thank you for the report.
